/*
 * File: app/model/Rule.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.model.Rule', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id',
            type: 'string'
        },
        {
            name: 'regexp',
            type: 'string'
        },
        {
            name: 'valore_note_3',
            type: 'string'
        },
        {
            name: 'scadenza',
            type: 'date'
        },
        {
            name: 'strategy',
            type: 'string'
        }
    ]
});