/*
 * File: app/store/Discounts.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.store.Discounts', {
    extend: 'Ext.data.Store',

    requires: [
        'ClothoExtXml.model.Discount'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'discounts',
            model: 'ClothoExtXml.model.Discount',
            data: [
                {
                    id: 1,
                    codice: 12345,
                    from_discount: 50,
                    to_discount: 60,
                    value_note_3: '40',
                    affiliato: 50,
                    affiliato_light: 60,
                    somministrato: 55,
                    scadenza: '2012-10-12'
                },
                {
                    id: 2,
                    codice: 12346,
                    from_discount: 55,
                    to_discount: 65,
                    value_note_3: '40',
                    affiliato: 55,
                    affiliato_light: 65,
                    somministrato: 60,
                    scadenza: '2012-10-12'
                },
                {
                    id: 3,
                    codice: 12347,
                    from_discount: 60,
                    to_discount: 70,
                    value_note_3: '40',
                    affiliato: 60,
                    affiliato_light: 70,
                    somministrato: 65,
                    scadenza: '2012-10-12'
                },
                {
                    id: 4,
                    codice: 12348,
                    from_discount: 65,
                    to_discount: 75,
                    value_note_3: '40',
                    affiliato: 65,
                    affiliato_light: 75,
                    somministrato: 70,
                    scadenza: '2012-10-12'
                },
                {
                    id: 5,
                    codice: 12349,
                    from_discount: 70,
                    to_discount: 80,
                    value_note_3: '40',
                    affiliato: 70,
                    affiliato_light: 80,
                    somministrato: 75,
                    scadenza: '2012-10-12'
                }
            ]
        }, cfg)]);
    }
});