/*
 * File: app/store/Prezzi.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.store.Prezzi', {
    extend: 'Ext.data.Store',

    requires: [
        'ClothoExtXml.model.Prezzo'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'prezzi',
            model: 'ClothoExtXml.model.Prezzo',
            data: [
                {
                    id: 1,
                    codice: 12345,
                    prezzo_from: 50,
                    prezzo_to: 70,
                    netto_lordo: 60,
                    prezzpPrezzoNL: 70,
                    prezzo_affiliato: 60,
                    prezzo_affiliato_light: 70,
                    prezzo_somministrato: 80,
                    scadenza: '2012-12-12'
                },
                {
                    id: 2,
                    codice: 12355,
                    prezzo_from: 60,
                    prezzo_to: 80,
                    netto_lordo: 70,
                    prezzpPrezzoNL: 80,
                    prezzo_affiliato: 70,
                    prezzo_affiliato_light: 80,
                    prezzo_somministrato: 900,
                    scadenza: '2012/12/12'
                },
                {
                    id: 3,
                    codice: 12365,
                    prezzo_from: 70,
                    prezzo_to: 90,
                    netto_lordo: 80,
                    prezzpPrezzoNL: 90,
                    prezzo_affiliato: 80,
                    prezzo_affiliato_light: 90,
                    prezzo_somministrato: 100,
                    scadenza: '2012/12/12'
                },
                {
                    id: 4,
                    codice: 12375,
                    prezzo_from: 80,
                    prezzo_to: 100,
                    netto_lordo: 90,
                    prezzpPrezzoNL: 100,
                    prezzo_affiliato: 90,
                    prezzo_affiliato_light: 100,
                    prezzo_somministrato: 110,
                    scadenza: '2012/12/12'
                },
                {
                    id: 5,
                    codice: 12385,
                    prezzo_from: 90,
                    prezzo_to: 110,
                    netto_lordo: 100,
                    prezzpPrezzoNL: 110,
                    prezzo_affiliato: 100,
                    prezzo_affiliato_light: 110,
                    prezzo_somministrato: 120,
                    scadenza: '2012/12/12'
                }
            ]
        }, cfg)]);
    }
});