/*
 * File: app/store/Rules.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.store.Rules', {
    extend: 'Ext.data.Store',

    requires: [
        'ClothoExtXml.model.Rule'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'rules',
            model: 'ClothoExtXml.model.Rule',
            data: [
                {
                    id: 'x',
                    regexp: 'xxx',
                    valore_note_3: '335',
                    scadenza: '2012/12/12',
                    strategy: 'code'
                },
                {
                    id: 'y',
                    regexp: 'yyy',
                    valore_note_3: '336',
                    scadenza: '2012/12/12',
                    strategy: 'desc'
                },
                {
                    id: 'z',
                    regexp: 'zzz',
                    valore_note_3: '337',
                    scadenza: '2012/12/12',
                    strategy: 'desccode'
                }
            ]
        }, cfg)]);
    }
});