/*
 * File: app/store/Vendors.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.store.Vendors', {
    extend: 'Ext.data.Store',

    requires: [
        'ClothoExtXml.model.Vendor'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'vendors',
            model: 'ClothoExtXml.model.Vendor',
            data: [
                {
                    id: 1,
                    codice: 12345,
                    nome: 'Safilo',
                    strategy: 'CODE'
                },
                {
                    id: 2,
                    codice: 23456,
                    nome: 'Luxottica',
                    strategy: 'DESC'
                },
                {
                    id: 3,
                    codice: 34567,
                    nome: 'Rodenstock',
                    strategy: 'DESCCODE'
                },
                {
                    id: 4,
                    codice: 45678,
                    nome: 'Hoya',
                    strategy: 'CODEDESC'
                }
            ]
        }, cfg)]);
    }
});