/*
 * File: app/view/BasicDataGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.BasicDataGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.basicDataGrid',

    height: 205,
    id: 'discountDataPanel',
    width: 748,
    title: 'Basic Data',
    store: 'Discounts',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Da'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'A'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Scadenza'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Valore in note3'
                }
            ]
        });

        me.callParent(arguments);
    }

});