/*
 * File: app/view/ClothoXmlViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.ClothoXmlViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'ClothoExtXml.view.VendorDataPanel',
        'ClothoExtXml.view.RulesAreaPanel',
        'ClothoExtXml.view.VendorArea',
        'ClothoExtXml.view.MainToolbar',
        'ClothoExtXml.controller.GlobalVariables'
    ],

    id: 'mainViewport',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'center',
                    id: 'centerRegion',
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'tabpanel',
                            id: 'mainTabset',
                            width: 694,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'vendorDataPanel'
                                },
                                {
                                    xtype: 'rulesAreaPanel',
                                    title: 'Regole di sconto'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'west',
                    maxWidth: 200,
                    width: 200,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'vendorArea'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'south',
                    height: 30
                },
                {
                    xtype: 'container',
                    region: 'north',
                    height: 34,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'mainToolbar',
                            flex: 2
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});