/*
 * File: app/view/DiscountGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.DiscountGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.discountGridPanel',

    height: 205,
    id: 'discountGridPanel',
    itemId: 'discountGridPanel',
    width: 748,
    title: 'Basic Data',
    store: 'Discounts',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'from_discount',
                    text: 'Da',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'to_discount',
                    text: 'A',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'value_note_3',
                    text: 'Valore in Note 3',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'scadenza',
                    text: 'Scadenza',
                    format: 'd/m/Y',
                    editor: {
                        xtype: 'datefield'
                    }
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.RowEditing', {
                    ptype: 'rowediting'
                })
            ]
        });

        me.callParent(arguments);
    }

});