/*
 * File: app/view/MainToolbar.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.MainToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.mainToolbar',

    height: 30,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    width: 53,
                    text: 'Excel'
                },
                {
                    xtype: 'button',
                    text: 'Diapason'
                },
                {
                    xtype: 'button',
                    width: 61,
                    text: 'Help'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'maintoolbar-add-btn',
                    iconCls: 'file_add',
                    text: 'Aggiungi',
                    listeners: {
                        click: {
                            fn: me.addRecord,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    id: 'maintoolbar-modify-btn',
                    iconCls: 'file_edit',
                    text: 'Modifica'
                },
                {
                    xtype: 'button',
                    id: 'maintoolbar-delete-btn',
                    iconCls: 'file_delete',
                    text: 'Cancella'
                },
                {
                    xtype: 'button',
                    id: 'bmaintoolbar-save-btn',
                    iconCls: 'file_save',
                    text: 'Salva'
                }
            ]
        });

        me.callParent(arguments);
    },

    addRecord: function(button, e, options) {
        console.log(ClothoExtXml.controller.GlobalVariables.getCurrentForm());
        console.log(ClothoExtXml.controller.GlobalVariables.getCurrentGrid());
        console.log(ClothoExtXml.controller.GlobalVariables.getCurrentRecord());
    }

});