/*
 * File: app/view/PrezziFissiGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.PrezziFissiGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.prezziFissiGridPanel',

    id: 'prezziFissiGridPanel',
    title: 'Prezzo fisso',
    store: 'PrezziFissi',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'prezzo_fornitore',
                    text: 'Prezzo_fornitore',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'netto_lordo',
                    text: 'Netto_lordo',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'affiliato',
                    text: 'Affiliato',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'affiliato_light',
                    text: 'Affiliato_light',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'somministrato',
                    text: 'Somministrato',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'scadenza',
                    text: 'Scadenza',
                    editor: {
                        xtype: 'datefield'
                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});