/*
 * File: app/view/RuleForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.RuleForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ruleForm',

    id: 'ruleForm',
    maxHeight: 220,
    minHeight: 220,
    padding: 2,
    bodyPadding: 5,
    title: 'Gestione singola regola',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    padding: 5,
                    width: 300,
                    title: 'Dati regola di sconto generica',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            width: 100,
                            name: 'regexp',
                            fieldLabel: 'Regola',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'valore_note_3',
                            fieldLabel: 'Valore',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            name: 'scadenza',
                            fieldLabel: 'Scadenza',
                            labelAlign: 'right',
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            name: 'strategy',
                            fieldLabel: 'Strategia',
                            labelAlign: 'right',
                            displayField: 'strategy',
                            store: 'Strategy',
                            valueField: 'strategy'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'button',
                            id: 'ruleFormSaveBtn',
                            iconCls: 'file_save',
                            text: 'Salva'
                        },
                        {
                            xtype: 'button',
                            id: 'ruleFormExit',
                            iconCls: 'cancel',
                            text: 'Esci senza salvare'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});