/*
 * File: app/view/ScontiGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.ScontiGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.scontiGridPanel',

    id: 'scontiGrid',
    padding: 2,
    title: 'Sconti',
    store: 'Sconti',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'sconto_fornitore',
                    text: 'Sconto_fornitore'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'tolleranza',
                    text: 'Tolleranza'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'prezzo_lordo',
                    text: 'Prezzo_lordo'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'affiliato',
                    text: 'Affiliato'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'affiliato_light',
                    text: 'Affiliato_light'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'somministrato',
                    text: 'Somministrato'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'prezzo_affiliato',
                    text: 'Prezzo_affiliato'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'prezzo_affiliato_light',
                    text: 'Prezzo_affiliato_light'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'prezzo_somministrato',
                    text: 'Prezzo_somministrato'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'scadenza',
                    text: 'Scadenza'
                }
            ]
        });

        me.callParent(arguments);
    }

});