/*
 * File: app/view/VendorForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.VendorForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.vendorForm',

    id: 'vendorForm',
    bodyPadding: 10,
    title: 'Gestione  Fornitore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    id: 'vendorFieldSet',
                    title: 'Dati generali del fornitore',
                    items: [
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'codiceVendor',
                            name: 'codice',
                            fieldLabel: 'Codice',
                            labelAlign: 'right',
                            labelWidth: 50,
                            hideTrigger: true,
                            spinDownEnabled: false,
                            spinUpEnabled: false,
                            allowDecimals: false,
                            decimalPrecision: 0
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'nomeVendor',
                            name: 'nome',
                            fieldLabel: 'Nome',
                            labelAlign: 'right',
                            labelWidth: 50,
                            size: 60
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            name: 'strategy',
                            fieldLabel: 'Strategia',
                            labelAlign: 'right',
                            labelWidth: 50,
                            displayField: 'strategy',
                            store: 'Strategy',
                            valueField: 'strategy'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 35,
                    maxHeight: 35,
                    minHeight: 35,
                    ui: 'footer',
                    layout: {
                        align: 'middle',
                        pack: 'center',
                        padding: '',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'venFormSaveBtn',
                            iconCls: 'file_save',
                            text: 'Salva'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'cancel',
                            text: 'Esci senza salvare',
                            type: 'reset',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        ClothoExtXml.controller.GlobalVariables.formExit();
    }

});