/*
 * File: app/view/VendorGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.VendorGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.vendorGridPanel',

    id: 'vendorGridPanel',
    title: 'Fornitori',
    store: 'Vendors',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 50,
                    dataIndex: 'codice',
                    text: 'Codice',
                    format: ''
                },
                {
                    xtype: 'gridcolumn',
                    width: 148,
                    dataIndex: 'nome',
                    text: 'Nome'
                }
            ],
            listeners: {
                afterlayout: {
                    fn: me.onVendorGridPanelAfterLayout,
                    scope: me
                },
                select: {
                    fn: me.onVendorGridPanelSelect,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onVendorGridPanelAfterLayout: function(abstractcontainer, layout, options) {
        ClothoExtXml.controller.GlobalVariables.setCurrentGrid(abstractcontainer);
    },

    onVendorGridPanelSelect: function(selModel, record, index, options) {
        Ext.getCmp('vendorData').update(record.getData());
    }

});