/*
 * File: app/view/VendorArea.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.VendorArea', {
    extend: 'Ext.container.Container',
    alias: 'widget.vendorArea',

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 200,
                    hidden: false,
                    id: 'vendorFormContainer',
                    maxHeight: 200,
                    minHeight: 200,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'form',
                            flex: 1,
                            bodyPadding: 10,
                            title: 'Gestione  Fornitore',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Dati generali del fornitore',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            name: 'codice',
                                            fieldLabel: 'Codice',
                                            labelAlign: 'right',
                                            labelWidth: 50,
                                            hideTrigger: true,
                                            spinDownEnabled: false,
                                            spinUpEnabled: false,
                                            allowDecimals: false,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            name: 'nome',
                                            fieldLabel: 'Nome',
                                            labelAlign: 'right',
                                            labelWidth: 50,
                                            size: 60
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            name: 'strategy',
                                            fieldLabel: 'Strategia',
                                            labelAlign: 'right',
                                            labelWidth: 50
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    height: 35,
                                    maxHeight: 35,
                                    minHeight: 35,
                                    ui: 'footer',
                                    layout: {
                                        align: 'middle',
                                        pack: 'center',
                                        padding: '',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'file_save',
                                            text: 'Salva',
                                            type: 'submit'
                                        },
                                        {
                                            xtype: 'button',
                                            iconCls: 'cancel',
                                            text: 'Esci senza salvare',
                                            type: 'reset',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 3,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'vendorGridPanel',
                            title: 'Fornitori',
                            store: 'Vendors',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    width: 50,
                                    dataIndex: 'codice',
                                    text: 'Codice',
                                    format: ''
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 148,
                                    dataIndex: 'nome',
                                    text: 'Nome'
                                }
                            ],
                            listeners: {
                                afterlayout: {
                                    fn: me.onVendorGridPanelAfterLayout,
                                    scope: me
                                },
                                select: {
                                    fn: me.onVendorGridPanelSelect,
                                    scope: me
                                },
                                itemdblclick: {
                                    fn: me.onVendorGridPanelItemDblClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        Ext.getCmp('vendorFormContainer').hide()
    },

    onVendorGridPanelAfterLayout: function(abstractcontainer, layout, options) {
        ClothoExtXml.controller.GlobalVariables.setCurrentGrid(abstractcontainer);
    },

    onVendorGridPanelSelect: function(selModel, record, index, options) {
        Ext.getCmp('vendorData').update(record.getData());
    },

    onVendorGridPanelItemDblClick: function(tablepanel, record, item, index, e, options) {
        Ext.getCmp('vendorFormContainer').show()
    }

});