/*
 * File: app/view/VendorArea.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.VendorArea', {
    extend: 'Ext.container.Container',
    alias: 'widget.vendorArea',

    requires: [
        'ClothoExtXml.view.VendorForm',
        'ClothoExtXml.view.VendorGridPanel'
    ],

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 200,
                    hidden: true,
                    id: 'vendorFormContainer',
                    maxHeight: 200,
                    minHeight: 200,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'vendorForm',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 3,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'vendorGridPanel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});