/*
 * File: app/view/VendorDataPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.view.VendorDataPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.vendorDataPanel',

    height: 613,
    width: 818,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Sconti generici',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    height: 205,
                    id: 'basicDataPanel',
                    width: 748,
                    title: 'Basic Data',
                    store: 'Discounts',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'from_discount',
                            text: 'Da'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'to_discount',
                            text: 'A'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'scadenza',
                            text: 'Scadenza'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'value_note_3',
                            text: 'Valore in note3'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});