/*
 * File: app/controller/FocusController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.controller.FocusController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.focusController',

    requires: [
        'ClothoExtXml.controller.GlobalVariables'
    ],

    init: function(application) {
        this.control(
        {'textfield': {'focus':this.fieldGotFocus},
        'gridpanel': {'containerclick':this.containerClicked}
    }
    )
    },

    fieldGotFocus: function(field) {
        console.log('Field has got focus: '+field.getName());
        this.resetBorders();
        var currentForm=field.up('form');
        currentForm.setBodyStyle('border-color','red');
        ClothoExtXml.controller.GlobalVariables.setCurrentForm(currentForm);
        ClothoExtXml.controller.GlobalVariables.setCurrentRecord(currentForm.getRecord());
    },

    resetBorders: function() {
        var panelsWithinMyViewport = Ext.ComponentQuery.query('gridpanel, form');
        Ext.Array.each(panelsWithinMyViewport,function(panel){
            panel.setBodyStyle('border-color','');
            //panel.setBodyStyle('border-width',0);
        })
    },

    containerClicked: function(view) {
        console.log('Container clicked');
        this.resetBorders();
        var currentForm=view.up('panel');
        currentForm.setBodyStyle('border-color','red');
        ClothoExtXml.controller.GlobalVariables.setCurrentGrid(currentForm);
    }

});
