/*
 * File: app/controller/GlobalVariables.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ClothoExtXml.controller.GlobalVariables', {
    extend: 'Ext.Base',

    singleton: true,

    setCurrentGrid: function(grid) {
        this.currentGrid=grid
    },

    setCurrentForm: function(form) {
        this.currentForm=form
    },

    setCurrentRecord: function(record) {
        this.currentRecord=record
    },

    setCurrentStatus: function(status) {
        this.currentStatus=status
    },

    getCurrentGrid: function() {
        return this.currentGrid
    },

    getCurrentForm: function() {
        return this.currentForm
    },

    getCurrentRecord: function() {
        return this.currentRecord
    },

    getCurrentStatus: function() {
        return this.currentStatus
    }

});